name: Build App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - run: npm install && npm run build
      - uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: '${{ github.token }}'
          publish_dir: ./dist
          force_orphan: true
